### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-mariavirum#1]
Buen trabajo @mariavirum !

### Algunas pistas para acabarlo:

- [x] En App.js usa los datos guardados en el estado para pasárselos al componente PokeList.
- [x] Si usas el hook `useState` y no usas la función `setLoQueSea` bórralo.
- [x] Elimina los constructores vacíos que no solo tienen dentro el `super(...)` ya que no aportan nada.
- [x] Importa los datos en App.js y no en PokeList.js
- [x] Usa el `id` de cada pokemon en el `li` para el `key` de react cuando mapeas y creas un listado de componentes: https://github.com/Adalab/modulo-3-evaluacion-intermedia-mariavirum/blob/master/src/components/PokeList.js#L9
- [x] Usa propTypes para comprobar el tipo de dato de las props

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by mariavirum** [comment]
Buenas Miguel, tengo dudas con las propTypes no sé si las he llamado correctamente.
Gracias por tu tiempo!

**Comment by migueldelmazo** [comment]
Hola @mariavirum, para saber si te están funcionando debes mirar la consola y si propTypes muestra algún Warning es que no lo estás haciendo bien.

No he probado el código en mi local pero creo que no está bien. Explicación:

Si tu props son `loQueSea` y `otraProp` en las props types debes poner:

```js
Pokemon.propTypes = {
  loQueSea: PropTypes.string,
  otraProp: PropTypes.string,
};
```

Como en tu ejercicio tienes la prop `props.pokemonsProp`, es decir tu prop es `pokemonsProp` que es (o esperamos que sea un objeto) y  tús propTypes deben ser algo como:

```js
Pokemon.propTypes = {
  pokemonsProp: PropTypes.object // esto solo comprueba que `pokemonsProp` es un objeto
};
```

Una forma más pro sería la siguiente:

```js
Pokemon.propTypes = {
  pokemonsProp: .shape({ // esto comprueba que `pokemonsProps` es un objeto, que a su vez tienen dentro una url de tipo texto y un name de tipo texto
    url: PropTypes.string,
    name: PropTypes.string
  }),
};
```

A por ello fiera!!!

**Comment by mariavirum** [comment]
Gracias Miguel!!! esta tarde me pongo con ello!!
